### ISSUE TITLE
Fix framework signing issue

### ISSUE THREAD

**Issue by nathanshelly** [natasha-codes/portals#3]

**Comment by sashaweiss** [comment]
we need to figure out how we're going to sign our code, in general.

the issue we were running into was that the MASShortcut `.framework` we load at runtime is not signed, since none of our code is signed, and there's a setting:

![image](https://user-images.githubusercontent.com/9013117/78326067-44b6d680-752e-11ea-8503-341612f505a3.png)

under "Signing and Capabilities" that prevents us from loading the unsigned library.

Temporary fix is to disable library validation:

![image](https://user-images.githubusercontent.com/9013117/78326105-59936a00-752e-11ea-99a0-aa63e192ac27.png)

but once we figure out how we're planning to sign our code we should put that setting back.

**Comment by sashaweiss** [comment]
pushed said change in ca0446ad4ef19ba0e47d1789c23a73a38a5c5fcf

**Comment by sashaweiss** [comment]
Have since disabled this hack. We will just need to keep switching our development team to our respective personal ones, but in the long-term future we can add separate debug and release configs that make this easier?
